apiVersion: apps/v1
kind: Deployment
metadata:
  name: ee-hello-world-v5
  labels:
    app: hello-world-app-v5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app-v5
  template:
    metadata:
      labels:
        app: hello-world-app-v5
    spec:
      containers:
      - name: hello-world
        image: flask-ee
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ee-helorld-service
spec:
  selector:
    app: hello-world-app-v5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: NodePort

